### ISSUE TITLE
Consider renaming this repo "guiltytargets-ppi"

### ISSUE THREAD

**Issue by cthoyt** [GuiltyTargets/ppi-network-annotation#2]
This makes it a bit more obvious that it's an extension to GuiltyTargets and will be used in concert.

**Comment by ozlemmuslu** [comment]
I thought of this as a more independent library for PPI network annotation in general, so people (e.g. new Master's students) can use it even if they don't work on GuiltyTargets

**Comment by cthoyt** [comment]
Okay, that's great!
